"""
Django settings for testdj project.

Generated by 'django-admin startproject' using Django 2.2.2.

For more information on this file, see
https://docs.djangoproject.com/en/2.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.2/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'j-q498+4qj04^pu%i7cq9i&e4792k^k_ps(5c*v1gkn*n(r3%j'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get('ESLJOBMAP_DEBUG', False)

ALLOWED_HOSTS = ['*']

INTERNAL_IPS = ('127.0.0.1', 'localhost')

# Application definition

INSTALLED_APPS = [
    'django_user_agents',
    'about',
    'account',
    'employment',
    'cloud',
    'blanket',
    'task',
    'job_credit',
    'payment',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'django_user_agents.middleware.UserAgentMiddleware',
]

ROOT_URLCONF = 'esljobmap.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [(os.path.join(BASE_DIR, 'templates'))],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'esljobmap.wsgi.application'


# Database
# https://docs.djangoproject.com/en/2.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': os.environ.get('ESLJOBMAP_DB_NAME', ''),
        'USER': os.environ.get('ESLJOBMAP_DB_USER', ''),
        'PASSWORD': os.environ.get('ESLJOBMAP_DB_PASSWORD'),
        'HOST': os.environ.get('ESLJOBMAP_DB_HOST'),
        'PORT': os.environ.get('ESLJOBMAP_DB_PORT')
    }
}


# Password validation
# https://docs.djangoproject.com/en/2.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/2.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = False

USE_L10N = False

USE_TZ = False


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.2/howto/static-files/

STATIC_ROOT = os.path.join(BASE_DIR, 'assets')
STATIC_URL = '/assets/'

STATICFILES_DIRS = [
    os.path.join(BASE_DIR, "static"),
]

# Custom Settings
AUTH_USER_MODEL = 'account.SiteUser'
AUTHENTICATION_BACKENDS = [
    'account.authbackend.UserAccountBackend'
]

LOGIN_URL = 'login'
LOGIN_REDIRECT_URL = 'account_profile'
LOGOUT_REDIRECT_URL = 'home'


EMAIL_HOST = 'smtp.mailgun.org'
EMAIL_PORT = 587
EMAIL_HOST_USER = os.environ.get('ESLJOBMAP_EMAIL_HOST_USER')
DEFAULT_FROM_EMAIL = os.environ.get('ESLJOBMAP_EMAIL_HOST_USER')
EMAIL_HOST_PASSWORD = os.environ.get('ESLJOBMAP_EMAIL_HOST_PASSWORD')
EMAIL_USE_TLS = True


CACHES = {
    "default": {
        "BACKEND": "django_redis.cache.RedisCache",
        "LOCATION": os.environ.get('ESLJOBMAP_REDIS_HOST', 'redis://127.0.0.1:6379/'),
        "OPTIONS": {
            "CLIENT_CLASS": "django_redis.client.DefaultClient"
        },
        "KEY_PREFIX": "esljobmap"
    }
}

SESSION_ENGINE = 'django.contrib.sessions.backends.cache'
