# Generated by Django 2.0.6 on 2019-01-17 15:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='can_transfer_visa',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='can_work_second_job',
        ),
        migrations.RemoveField(
            model_name='visatype',
            name='email_text',
        ),
    ]
