# Generated by Django 2.0.6 on 2019-02-06 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20190117_1509'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteuser',
            name='is_banned',
            field=models.BooleanField(default=False),
        ),
    ]
