# Generated by Django 2.0.6 on 2019-03-03 11:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_siteuser_opted_out_of_expired_job_emails'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='siteuser',
            name='contact_email',
        ),
    ]
