# Generated by Django 2.0.6 on 2019-03-30 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_remove_siteuser_contact_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siteuser',
            name='opted_out_of_emails',
            field=models.BooleanField(default=False, verbose_name='Don’t receive copy of application emails'),
        ),
        migrations.AlterField(
            model_name='siteuser',
            name='opted_out_of_expired_job_emails',
            field=models.BooleanField(default=False, verbose_name='Don’t receive job expire notification emails'),
        ),
    ]
