# Generated by Django 2.2 on 2019-05-01 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_auto_20190330_0151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siteuser',
            name='is_banned',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='siteuser',
            name='opted_out_of_emails',
            field=models.BooleanField(blank=True, default=False, verbose_name='Don’t receive copy of application emails'),
        ),
        migrations.AlterField(
            model_name='siteuser',
            name='opted_out_of_expired_job_emails',
            field=models.BooleanField(blank=True, default=False, verbose_name='Don’t receive job expire notification emails'),
        ),
    ]
