# Generated by Django 2.0.6 on 2019-04-09 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_auto_20190330_0151'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteuser',
            name='job_credits',
            field=models.FloatField(blank=True, default=0),
        ),
    ]
