# Generated by Django 2.2 on 2019-07-01 13:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_auto_20190501_0933'),
    ]

    operations = [
        migrations.CreateModel(
            name='AutofillOptions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ft_other_requirements', models.CharField(blank=True, default='', max_length=1024)),
                ('ft_salary', models.CharField(blank=True, default='', max_length=512)),
                ('ft_benefits', models.CharField(blank=True, default='', max_length=1024)),
                ('pt_class_type', models.CharField(max_length=255)),
                ('pt_schedule', models.CharField(max_length=512)),
                ('pt_pay_rate', models.CharField(blank=True, default='', max_length=512)),
                ('pt_other_requirements', models.CharField(blank=True, default='', max_length=1024)),
                ('site_user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='autofill_options', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'account_autofill_options',
            },
        ),
    ]
