# Generated by Django 2.2 on 2019-07-28 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_autofilloptions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='autofilloptions',
            name='ft_benefits',
            field=models.CharField(blank=True, default='', max_length=1024, verbose_name='Benefits'),
        ),
        migrations.AlterField(
            model_name='autofilloptions',
            name='ft_other_requirements',
            field=models.CharField(blank=True, default='', max_length=1024, verbose_name='Other requirements'),
        ),
        migrations.AlterField(
            model_name='autofilloptions',
            name='ft_salary',
            field=models.CharField(blank=True, default='', max_length=512, verbose_name='Salary'),
        ),
        migrations.AlterField(
            model_name='autofilloptions',
            name='pt_class_type',
            field=models.CharField(max_length=255, verbose_name='Class type'),
        ),
        migrations.AlterField(
            model_name='autofilloptions',
            name='pt_other_requirements',
            field=models.CharField(blank=True, default='', max_length=1024, verbose_name='Other requirements'),
        ),
        migrations.AlterField(
            model_name='autofilloptions',
            name='pt_pay_rate',
            field=models.CharField(blank=True, default='', max_length=512, verbose_name='Pay rate'),
        ),
        migrations.AlterField(
            model_name='autofilloptions',
            name='pt_schedule',
            field=models.CharField(max_length=512, verbose_name='Schedule'),
        ),
    ]
