# Generated by Django 2.2 on 2019-09-24 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_auto_20190728_1613'),
    ]

    operations = [
        migrations.AddField(
            model_name='autofilloptions',
            name='ft_class_type',
            field=models.CharField(blank=True, max_length=255, verbose_name='Class type'),
        ),
        migrations.AlterField(
            model_name='autofilloptions',
            name='pt_class_type',
            field=models.CharField(blank=True, max_length=255, verbose_name='Class type'),
        ),
        migrations.AlterField(
            model_name='autofilloptions',
            name='pt_schedule',
            field=models.CharField(blank=True, max_length=512, verbose_name='Schedule'),
        ),
    ]
