# Generated by Django 2.2 on 2019-05-06 16:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Charge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stripe_charge_id', models.CharField(max_length=1024)),
                ('status', models.CharField(choices=[('completed', 'Completed'), ('refunded', 'Refunded')], default='completed', max_length=128)),
                ('site_user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='payment_charges', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
