# Generated by Django 2.2 on 2019-08-11 10:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0003_auto_20190811_1017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='plan', to='payment.Product'),
        ),
    ]
