# Generated by Django 2.2 on 2019-08-25 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0004_auto_20190811_1021'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='short_descriptor',
            field=models.CharField(default='', max_length=128),
        ),
    ]
