# Generated by Django 2.0.6 on 2018-11-11 00:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DisinterestedJobPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'employment_disinterested_job_post',
            },
        ),
        migrations.CreateModel(
            name='JobApplication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_email', models.EmailField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'employment_job_application',
            },
        ),
        migrations.CreateModel(
            name='JobPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=512)),
                ('class_type', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=512)),
                ('contact_name', models.CharField(max_length=512)),
                ('contact_email', models.EmailField(max_length=255)),
                ('contact_number', models.CharField(max_length=255)),
                ('schedule', models.CharField(max_length=512)),
                ('other_requirements', models.CharField(blank=True, default='', max_length=1024)),
                ('is_full_time', models.BooleanField(default=False, verbose_name='Job type')),
                ('pay_rate', models.CharField(blank=True, default='', max_length=512)),
                ('salary', models.CharField(blank=True, default='', max_length=512)),
                ('benefits', models.CharField(blank=True, default='', max_length=1024)),
                ('is_visible', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('latitude', models.FloatField(default=0)),
                ('longitude', models.FloatField(default=0)),
                ('address', models.CharField(default='', max_length=1024)),
                ('is_archived', models.BooleanField(default=False)),
                ('site_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_posts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'employment_job_post',
            },
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='job_post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applicants', to='employment.JobPost'),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='resume',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.Resume'),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='site_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='job_applications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='disinterestedjobpost',
            name='job_post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employment.JobPost'),
        ),
        migrations.AddField(
            model_name='disinterestedjobpost',
            name='site_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disinterested_job_posts', to=settings.AUTH_USER_MODEL),
        ),
    ]
