# Generated by Django 2.0.6 on 2018-07-10 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JobPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=512)),
                ('class_type', models.CharField(max_length=255, verbose_name='The type of class the teaching job entails')),
                ('location', models.CharField(max_length=512)),
                ('contact_name', models.CharField(max_length=512)),
                ('contact_email', models.EmailField(max_length=255)),
                ('contact_number', models.CharField(max_length=255)),
                ('schedule', models.CharField(max_length=512)),
                ('other_requirements', models.TextField()),
                ('is_full_time', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'employment_job_post',
            },
        ),
    ]
