# Generated by Django 2.0.6 on 2018-11-03 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobpost',
            name='is_archived',
            field=models.BooleanField(default=False),
        ),
    ]
