# Generated by Django 2.0.6 on 2019-02-17 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobpost',
            name='reposted_at',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
