# Generated by Django 2.0.6 on 2018-12-28 12:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employment', '0002_remove_jobpost_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobpost',
            name='is_archived',
        ),
    ]
