# Generated by Django 2.0.6 on 2018-11-04 01:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('employment', '0002_jobpost_is_archived'),
    ]

    operations = [
        migrations.CreateModel(
            name='DisinterestedJobPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employment.JobPost')),
                ('site_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disinterested_job_posts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'employment_disinterested_job_post',
            },
        ),
    ]
