# Generated by Django 2.0.6 on 2019-02-24 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employment', '0002_jobpost_reposted_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobpost',
            name='expiry_notice_sent',
            field=models.BooleanField(default=False),
        ),
    ]
