# Generated by Django 2.0.6 on 2019-01-12 23:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_auto_20190112_2321'),
        ('employment', '0003_remove_jobpost_is_archived'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapplication',
            name='photo',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='account.Photo'),
        ),
    ]
