# Generated by Django 2.0.6 on 2018-09-02 16:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employment', '0003_auto_20180812_2316'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapplication',
            name='resume_filename',
            field=models.CharField(default='', max_length=512),
        ),
        migrations.AlterField(
            model_name='jobapplication',
            name='job_post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applicants', to='employment.JobPost'),
        ),
        migrations.AlterModelTable(
            name='jobapplication',
            table='employment_job_application',
        ),
    ]
