# Generated by Django 2.0.6 on 2019-03-03 11:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employment', '0004_jobpost_created_at_override'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobpost',
            name='contact_email',
        ),
    ]
