# Generated by Django 2.0.6 on 2018-09-10 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employment', '0004_auto_20180902_1626'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapplication',
            name='use_existing_resume',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='jobapplication',
            name='resume_filename',
            field=models.CharField(blank=True, default='', max_length=512),
        ),
    ]
