# Generated by Django 2.0.6 on 2019-01-15 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employment', '0005_auto_20190113_0851'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobpost',
            name='title',
            field=models.CharField(max_length=50),
        ),
    ]
