# Generated by Django 2.0.6 on 2019-03-10 18:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employment', '0005_remove_jobpost_contact_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobpost',
            name='contact_name',
        ),
        migrations.RemoveField(
            model_name='jobpost',
            name='contact_number',
        ),
    ]
