# Generated by Django 2.0.6 on 2018-09-16 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employment', '0005_auto_20180910_0144'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobpost',
            name='address',
            field=models.CharField(default='', max_length=1024),
        ),
        migrations.AddField(
            model_name='jobpost',
            name='latitude',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='jobpost',
            name='longitude',
            field=models.FloatField(default=0),
        ),
    ]
