# Generated by Django 2.0.6 on 2019-03-31 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employment', '0006_auto_20190310_1801'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobpost',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='jobpost',
            name='posted_at',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
