# Generated by Django 2.0.6 on 2018-10-14 04:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_auto_20181014_0455'),
        ('employment', '0006_auto_20180916_0838'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobapplication',
            name='resume_filename',
        ),
        migrations.RemoveField(
            model_name='jobapplication',
            name='use_existing_resume',
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='resume',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='account.Resume'),
            preserve_default=False,
        ),
    ]
