# Generated by Django 2.0.6 on 2019-03-02 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employment', '0003_jobpost_expiry_notice_sent'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobpost',
            name='created_at_override',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
