# Generated by Django 2.2 on 2019-05-01 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employment', '0007_auto_20190331_1051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobpost',
            name='expiry_notice_sent',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
