# Generated by Django 2.2 on 2019-06-16 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employment', '0008_auto_20190501_0933'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobpost',
            name='was_cloned',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
