# Generated by Django 2.2 on 2019-08-11 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employment', '0009_jobpost_was_cloned'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobpost',
            name='is_subscription_job',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='jobpost',
            name='is_suspended',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
