# Generated by Django 2.0.6 on 2018-09-09 09:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='resume_filename',
            field=models.CharField(blank=True, default='', max_length=512, verbose_name='Resume'),
        ),
        migrations.AlterField(
            model_name='country',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Nationality'),
        ),
        migrations.AlterField(
            model_name='siteuser',
            name='first_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='First Name'),
        ),
        migrations.AlterField(
            model_name='siteuser',
            name='last_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Last Name'),
        ),
        migrations.AlterField(
            model_name='siteuser',
            name='phone_number',
            field=models.CharField(blank=True, max_length=255, verbose_name='Contact Number'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='account.Country', verbose_name='Nationality'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='visa_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='account.VisaType', verbose_name='Visa Status'),
        ),
    ]
