# Generated by Django 2.0.6 on 2018-12-28 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='resume',
            old_name='filename',
            new_name='unique_filename',
        ),
        migrations.AddField(
            model_name='resume',
            name='original_filename',
            field=models.CharField(default='', max_length=512),
        ),
    ]
