# Generated by Django 2.0.6 on 2018-11-18 21:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='visatype',
            name='email_text',
            field=models.CharField(default='', max_length=512),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='country',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='account.Country', verbose_name='Nationality'),
        ),
    ]
