# Generated by Django 2.0.6 on 2018-11-04 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='can_transfer_visa',
            field=models.BooleanField(default=False, verbose_name='My visa can be transferred to new employer'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='can_work_second_job',
            field=models.BooleanField(default=False, verbose_name='My current employer has given permission to work a second job'),
        ),
    ]
