# Generated by Django 2.0.6 on 2018-10-14 04:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20180909_0911'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(default='', max_length=512)),
                ('created_at_date', models.DateTimeField(auto_now_add=True, verbose_name='Date Uploaded')),
            ],
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='resume_filename',
        ),
        migrations.AddField(
            model_name='teacher',
            name='resume',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='account.Resume'),
        ),
    ]
