# Generated by Django 2.0.6 on 2019-01-12 23:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20181228_0842'),
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_filename', models.CharField(default='', max_length=512)),
                ('unique_filename', models.CharField(default='', max_length=512)),
                ('created_at_date', models.DateTimeField(auto_now_add=True, verbose_name='Date Uploaded')),
            ],
        ),
        migrations.AddField(
            model_name='siteuser',
            name='contact_email',
            field=models.EmailField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='siteuser',
            name='name',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='resume',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='account.Resume'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='photo',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='account.Photo'),
        ),
    ]
