# Generated by Django 2.0.6 on 2019-01-12 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20181228_0842'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteuser',
            name='contact_email',
            field=models.EmailField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='siteuser',
            name='name',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Name'),
        ),
    ]
