# Generated by Django 2.0.6 on 2019-02-28 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_siteuser_is_banned'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteuser',
            name='opted_out_of_expired_job_emails',
            field=models.BooleanField(default=False, verbose_name='Don’t receive an expiry notice email'),
        ),
    ]
