# Generated by Django 2.0.6 on 2019-01-13 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_auto_20190112_2321'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteuser',
            name='opted_out_of_emails',
            field=models.BooleanField(default=False),
        ),
    ]
