# Generated by Django 2.0.6 on 2019-01-15 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_siteuser_opted_out_of_emails'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siteuser',
            name='opted_out_of_emails',
            field=models.BooleanField(default=False, verbose_name='Don’t receive an email copy of applications'),
        ),
    ]
